DECODING_GAMMA = 0.4545
ENCODING_GAMMA = 2.2


SWITCH_SWIZZLE_MODE = 4

HEIGHT_OF_IMAGE_CANVAS, WIDTH_OF_IMAGE_CANVAS = 256, 256
BYTES_PER_BLOCK_SWITCH_CANVAS = 4
UNCOMPRESSED_BLOCK_SIZE_CANVAS = (1, 1)

HEIGHT_OF_IMAGE_TEXTURE, WIDTH_OF_IMAGE_TEXTURE = 512, 512
BYTES_PER_BLOCK_SWITCH_TEXTURE = 8
UNCOMPRESSED_BLOCK_SIZE_TEXTURE = (4, 4)

HEIGHT_OF_IMAGE_TEXTURE_NON_FACEPAINT, WIDTH_OF_IMAGE_TEXTURE_NON_FACEPAINT = 384, 384
UNCOMPRESSED_BLOCK_SIZE_TEXTURE_NON_FACEPAINT = (4, 3)

FILE_FORMAT = "png"
SRGB_PROFILE = "sRGB"
IMAGE_MODE = "RGBA"
