from PIL import Image, ImageCms
from constants import *
from helper_functions import *
import compression.zstd as zstd
import io
from pyswizzle import nsw_deswizzle, nsw_swizzle
import sys
import os
import struct

"""
For converting textures.
Such as UgcCloth000.ugctex.zs or UgcFacePaint000.ugctex.zs
Simply drag and drop a png onto this script to convert a png into a .ugctex.zs or a .ugctex.zs to convert it into a png

Beware, this python script is quite untested
"""

"""
These lengths are copied from github.com/Timiimiimii/TomoKoreFacepaintTool/pull/6/changes - a pull request by KLanausse "Fix exporting non-facepaint UGC Textures"
"""
RAWDATA_LENGTHS = {
    131072: {
        "Dimensions": (HEIGHT_OF_IMAGE_TEXTURE, WIDTH_OF_IMAGE_TEXTURE),
        "Uncompressed_block_size": UNCOMPRESSED_BLOCK_SIZE_TEXTURE
    },
    98304: {
        "Dimensions": (HEIGHT_OF_IMAGE_TEXTURE_NON_FACEPAINT, WIDTH_OF_IMAGE_TEXTURE_NON_FACEPAINT),
        "Uncompressed_block_size": UNCOMPRESSED_BLOCK_SIZE_TEXTURE_NON_FACEPAINT
    },
}

IMAGE_SIZE_LENGTHS = {
    (512, 512): 131072,
    (384, 384): 98304
}


def make_dds_header(width, height):
    """
    THIS METHOD IS GENERATED BY CLAUDE SONNET 4.6 BEWARE
    Build a DDS header for a DXT1 texture with the given pixel dimensions.

    The original code used a single hardcoded DDS_HEADER constant that always
    described a 512x512 image.
    """
    hdr = b'DDS '
    hdr += struct.pack('<I', 124)                         # dwSize
    # dwFlags: CAPS|HEIGHT|WIDTH|PIXELFORMAT
    hdr += struct.pack('<I', 0x1 | 0x2 | 0x4 | 0x1000)
    hdr += struct.pack('<I', height)                      # dwHeight
    hdr += struct.pack('<I', width)                       # dwWidth
    # dwPitchOrLinearSize (DXT1: 8 bytes per 4x4 block)
    hdr += struct.pack('<I', max(1, width // 4) * 8)
    # dwDepth, dwMipMapCount
    hdr += struct.pack('<II', 0, 1)
    hdr += b'\x00' * 44                                  # dwReserved1[11]
    # DDPIXELFORMAT
    hdr += struct.pack('<I', 32)                         # pf.dwSize
    # pf.dwFlags = DDPF_FOURCC
    hdr += struct.pack('<I', 0x4)
    hdr += b'DXT1'                                       # pf.dwFourCC
    # bitcount + masks (unused for FOURCC)
    hdr += b'\x00' * 20
    # DDCAPS2
    # dwCaps = DDSCAPS_TEXTURE
    hdr += struct.pack('<I', 0x1000)
    hdr += b'\x00' * 16
    assert len(hdr) == 128, f"DDS header must be 128 bytes, got {len(hdr)}"
    return hdr


def save_ugctex(img: Image, imagepath: Path):
    dds_bytes = io.BytesIO()
    img.save(dds_bytes, format='DDS', pixel_format='DXT1')

    save_ugctex_path = imagepath.with_name(f"{imagepath.stem}.ugctex.zs")

    if img.size in IMAGE_SIZE_LENGTHS:
        rawdata_length = RAWDATA_LENGTHS[IMAGE_SIZE_LENGTHS[img.size]]
        rawdata_dimensions = rawdata_length["Dimensions"]
        rawdata_uncompressed_block_size = rawdata_length["Uncompressed_block_size"]
        ugctex_swizzled_data = nsw_swizzle(dds_bytes.getvalue()[128:], rawdata_dimensions,
                                           rawdata_uncompressed_block_size, BYTES_PER_BLOCK_SWITCH_TEXTURE, SWITCH_SWIZZLE_MODE)
        check_if_path_exists(save_ugctex_path)
        ugctex_swizzled_data = zstd.compress(ugctex_swizzled_data)
        with open(save_ugctex_path, 'wb') as f:
            f.write(bytes(ugctex_swizzled_data))
    else:
        print(
            f"imgsize for texture conversion is not in one of the expected dimensions {IMAGE_SIZE_LENGTHS.keys()}")


def convert_ugctex_to_png(ugctext_path):
    with open(ugctext_path, 'rb') as file:
        rawdata = file.read()
        if ugctext_path.name.endswith(".zs"):
            rawdata = zstd.decompress(rawdata)
        rawdata_length = len(rawdata)
        if rawdata_length in RAWDATA_LENGTHS:
            rawdata_values = RAWDATA_LENGTHS[rawdata_length]
            swizzled = nsw_deswizzle(rawdata, rawdata_values["Dimensions"],
                                     rawdata_values["Uncompressed_block_size"], BYTES_PER_BLOCK_SWITCH_TEXTURE, SWITCH_SWIZZLE_MODE)
            dds_header = make_dds_header(
                rawdata_values["Dimensions"][1], rawdata_values["Dimensions"][0])
            img = Image.open(io.BytesIO(dds_header + swizzled))

            save_file(img, ugctext_path)
        else:
            print(
                f"rawdata for texture conversion is not in one of the expected dimensions {RAWDATA_LENGTHS.keys()}")


def convert_png_to_ugctex(ugctex_path):
    ugctex = Image.open(Path.cwd() / ugctex_path)
    if not is_srgb_image(ugctex):
        ugctex = set_image_gamma(ugctex, ENCODING_GAMMA)

    """
    Todo: readd asserts from the valid ugctex sizes
    """

    save_ugctex(ugctex, ugctex_path)


if __name__ == "__main__":
    if len(sys.argv) > 1:
        files = sys.argv[1:]
        for path in files:
            if os.path.exists(os.path.abspath(path)):
                if path.endswith("ugctex.zs"):
                    convert_ugctex_to_png(Path.cwd() / path)
                elif path.endswith(".png"):
                    convert_png_to_ugctex(Path.cwd() / path)
                else:
                    print("File extension unrecognized.")
            else:
                print(f"File {path} doesn't exist.")
    else:
        convert_ugctex_to_png(Path.cwd() / "UgcFood000.ugctex.zs")
        pass
        # convert_png_to_ugctex(Path.cwd() / "UgcCloth003OUTPUT.png")
